# Generated by Django 3.2.9 on 2021-12-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='URL Curta')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('banned', models.BooleanField(verbose_name='Banido')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Senha')),
                ('expire_in', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('target', models.CharField(max_length=2040, verbose_name='URL Original')),
                ('visit_count', models.IntegerField(verbose_name='Quantidade de visitas')),
                ('created_at', models.DateTimeField(verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(verbose_name='Atualizado em')),
                ('uuid', models.UUIDField()),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'db_table': 'links',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apikey', models.CharField(blank=True, max_length=255, null=True)),
                ('banned', models.BooleanField(verbose_name='Banido')),
                ('cooldowns', models.TextField(blank=True, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255, verbose_name='Senha')),
                ('reset_password_expires', models.DateTimeField(blank=True, null=True)),
                ('reset_password_token', models.CharField(blank=True, max_length=255, null=True)),
                ('change_email_expires', models.DateTimeField(blank=True, null=True)),
                ('change_email_token', models.CharField(blank=True, max_length=255, null=True)),
                ('change_email_address', models.CharField(blank=True, max_length=255, null=True)),
                ('verification_expires', models.DateTimeField(blank=True, null=True)),
                ('verification_token', models.CharField(blank=True, max_length=255, null=True)),
                ('verified', models.BooleanField(verbose_name='Verificado')),
                ('created_at', models.DateTimeField(verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
