# Generated by Django 3.2.9 on 2021-12-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banned', models.BooleanField()),
                ('address', models.CharField(max_length=255, unique=True)),
                ('homepage', models.CharField(blank=True, max_length=255, null=True)),
                ('uuid', models.UUIDField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'domains',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True)),
                ('banned', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'hosts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ips',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('referrers', models.JSONField(blank=True, null=True)),
                ('total', models.IntegerField()),
                ('br_chrome', models.IntegerField()),
                ('br_edge', models.IntegerField()),
                ('br_firefox', models.IntegerField()),
                ('br_ie', models.IntegerField()),
                ('br_opera', models.IntegerField()),
                ('br_other', models.IntegerField()),
                ('br_safari', models.IntegerField()),
                ('os_android', models.IntegerField()),
                ('os_ios', models.IntegerField()),
                ('os_linux', models.IntegerField()),
                ('os_macos', models.IntegerField()),
                ('os_other', models.IntegerField()),
                ('os_windows', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'db_table': 'visits',
                'managed': False,
            },
        ),
    ]
