# Generated by Django 3.2.9 on 2021-12-12 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kutt', '0002_domains_hosts_ips_knexmigrations_knexmigrationslock_visits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domains',
            options={'managed': False, 'verbose_name': 'Domínio', 'verbose_name_plural': 'Domínios'},
        ),
        migrations.AlterModelOptions(
            name='hosts',
            options={'managed': False, 'verbose_name': 'Host', 'verbose_name_plural': 'Hosts'},
        ),
        migrations.AlterModelOptions(
            name='ips',
            options={'managed': False, 'verbose_name': 'IP', 'verbose_name_plural': 'IPs'},
        ),
    ]
